# Generated by Django 4.2.11 on 2024-05-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushing',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='Project Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bushing',
            name='bushingName',
            field=models.CharField(max_length=32, verbose_name='Bushing Name'),
        ),
    ]
