# Generated by Django 4.2.11 on 2024-06-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='partsNumber',
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Program'),
        ),
    ]
