# Generated by Django 4.2.11 on 2024-06-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='partName',
            field=models.CharField(max_length=128, verbose_name='Part Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=128, unique=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectNo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Project No'),
        ),
    ]
