# Generated by Django 4.2.11 on 2024-06-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_project_partsnumber_project_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='theoHeight',
        ),
        migrations.RemoveField(
            model_name='link',
            name='linkType',
        ),
    ]
