# Generated by Django 4.2.11 on 2024-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_bushing_project_alter_bushing_bushingname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bushing',
            name='defaultInterfaceHeight',
        ),
        migrations.RemoveField(
            model_name='bushing',
            name='defaultInterfaceIntDiam',
        ),
        migrations.AddField(
            model_name='part',
            name='defaultInterfaceHeight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Default Interface Height[mm]'),
        ),
        migrations.AddField(
            model_name='part',
            name='defaultInterfaceIntDiam',
            field=models.IntegerField(blank=True, null=True, verbose_name='Default Interface Int. Diam.[mm]'),
        ),
    ]
