# Generated by Django 4.2.11 on 2024-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_interface_theoheight_remove_link_linktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='projectImage',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Project Image'),
        ),
    ]
