# Generated by Django 4.2.11 on 2024-05-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_bushing_defaultinterfaceheight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.part', verbose_name='Part Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interface',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='Project Name'),
            preserve_default=False,
        ),
    ]
