# Generated by Django 4.2.11 on 2024-05-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_bushing_interface_link_part_project_user_winding_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='interface1',
            new_name='interface',
        ),
        migrations.RenameField(
            model_name='winding',
            old_name='interface1',
            new_name='interface',
        ),
        migrations.AlterField(
            model_name='bushing',
            name='bushingDrawNb',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Bushing Draw. Nb'),
        ),
        migrations.AlterField(
            model_name='part',
            name='defaultLinkDefined',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Default Link defined by'),
        ),
        migrations.AlterField(
            model_name='part',
            name='defaultLinkType',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Default Link(Element) Type'),
        ),
        migrations.AlterField(
            model_name='part',
            name='fiberName',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='FiberName'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_csv',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Document.csv'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_gh',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Document.gh'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_jpg',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Document.jpg'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_log',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Document.log'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_mod',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Document.mod'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_mp4',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Document.mp4'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_rs',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Document.rs'),
        ),
        migrations.AlterField(
            model_name='part',
            name='projectImage',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='part',
            name='resinName',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Resin Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='documentNb',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Document Nr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.CharField(max_length=32, null=True, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Update M/D/Y'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partsNumber',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Parts Number'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectNo',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Project No'),
        ),
        migrations.AlterField(
            model_name='project',
            name='relativeDesign',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Relative Design'),
        ),
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Revision'),
        ),
        migrations.AlterField(
            model_name='project',
            name='structureDrawingNb',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Structure Drawing Nb'),
        ),
    ]
