# Generated by Django 4.2.11 on 2024-05-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_interface_bushing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='LinkName',
            new_name='linkName',
        ),
    ]
