# Generated by Django 4.2.11 on 2024-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_delete_admin_rename_interface1_link_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Equipment'),
        ),
    ]
