# Generated by Django 4.2.11 on 2024-06-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='object_id',
            field=models.CharField(max_length=50),
        ),
    ]
