# Generated by Django 4.2.11 on 2024-06-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_log_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='model',
            field=models.CharField(max_length=255),
        ),
    ]
