# Generated by Django 4.2.11 on 2024-05-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_linkname_link_linkname'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='interface1',
            field=models.CharField(default=1, max_length=32, verbose_name='Interface1 Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='interface2',
            field=models.CharField(default=1, max_length=32, verbose_name='Interface2 Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='Project Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=16, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='finAccSection',
            field=models.FloatField(blank=True, null=True, verbose_name='Fin. Acc. Section[mm²]'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='totalSection',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Section[mm²]'),
        ),
        migrations.AlterField(
            model_name='link',
            name='armSection',
            field=models.FloatField(blank=True, max_length=32, null=True, verbose_name='Arm Section[mm²]'),
        ),
        migrations.AlterField(
            model_name='link',
            name='finArmSection',
            field=models.FloatField(blank=True, null=True, verbose_name='Fin. Arm Section[mm²]'),
        ),
        migrations.AlterField(
            model_name='part',
            name='fiberSectionAcc',
            field=models.FloatField(blank=True, null=True, verbose_name='Fiber Section acc.[mm²]'),
        ),
        migrations.AlterField(
            model_name='part',
            name='fiberSectionCalc',
            field=models.FloatField(blank=True, null=True, verbose_name='Fiber Section calc.[mm²]'),
        ),
    ]
