# Generated by Django 4.2.11 on 2024-05-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_link_interface1_link_interface2_link_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='interface',
        ),
    ]
