# Generated by Django 4.2.11 on 2024-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_link_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushing',
            name='bushingDrawNb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bushing Draw. Nb'),
        ),
        migrations.AlterField(
            model_name='bushing',
            name='bushingName',
            field=models.CharField(max_length=255, verbose_name='Bushing Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='interfaceName',
            field=models.CharField(max_length=255, verbose_name='Interface Name'),
        ),
        migrations.AlterField(
            model_name='link',
            name='armSection',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Arm Section[mm²]'),
        ),
        migrations.AlterField(
            model_name='link',
            name='interface1',
            field=models.CharField(max_length=255, verbose_name='Interface1 Name'),
        ),
        migrations.AlterField(
            model_name='link',
            name='interface2',
            field=models.CharField(max_length=255, verbose_name='Interface2 Name'),
        ),
        migrations.AlterField(
            model_name='link',
            name='linkName',
            field=models.CharField(max_length=255, verbose_name='Link Name'),
        ),
        migrations.AlterField(
            model_name='link',
            name='linkType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Type'),
        ),
        migrations.AlterField(
            model_name='link',
            name='sequence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='part',
            name='defaultLinkDefined',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Link defined by'),
        ),
        migrations.AlterField(
            model_name='part',
            name='defaultLinkType',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Link(Element) Type'),
        ),
        migrations.AlterField(
            model_name='part',
            name='fiberName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FiberName'),
        ),
        migrations.AlterField(
            model_name='part',
            name='partName',
            field=models.CharField(max_length=255, unique=True, verbose_name='Part Name'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_csv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document.csv'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_gh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document.gh'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_jpg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document.jpg'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_log',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document.log'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_mod',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document.mod'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_mp4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document.mp4'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_rs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document.rs'),
        ),
        migrations.AlterField(
            model_name='part',
            name='resinName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resin Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='documentNb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document Nr'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=255, unique=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectNo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project No'),
        ),
        migrations.AlterField(
            model_name='project',
            name='relativeDesign',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Relative Design'),
        ),
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Revision'),
        ),
        migrations.AlterField(
            model_name='project',
            name='structureDrawingNb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Structure Drawing Nb'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='windingtype',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
    ]
