# Generated by Django 4.2.11 on 2024-05-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_bushing_bushingdrawnb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='1a7928232fd865f75808759d0ab8d24f', max_length=255, verbose_name='Password'),
        ),
    ]
