# Generated by Django 4.2.11 on 2024-05-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='partsNumber',
        ),
        migrations.AddField(
            model_name='project',
            name='quantityOfPart',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity Of Part'),
        ),
    ]
