# Generated by Django 4.2.11 on 2024-06-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_log_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winding',
            name='sequence',
        ),
    ]
