# Generated by Django 4.2.11 on 2024-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_winding_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='projectImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Project Image'),
        ),
    ]
