# Generated by Django 4.2.11 on 2024-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_fiber_r_and_d_rdcomment_resin_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='quantityOfPart',
        ),
        migrations.AddField(
            model_name='project',
            name='partsNumber',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Parts'),
        ),
    ]
