# Generated by Django 4.2.11 on 2024-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_project_quantityofpart_project_partsnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiber',
            name='price21',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price euros/kg (2021 to febrary 2022)'),
        ),
        migrations.AddField(
            model_name='fiber',
            name='price22',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price euros/kg (after 02/2022)'),
        ),
        migrations.AddField(
            model_name='fiber',
            name='price23',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price euros/kg (after 02/2023)'),
        ),
        migrations.AddField(
            model_name='fiber',
            name='price24',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price euros/kg (after 01/2024)'),
        ),
    ]
