# Generated by Django 4.2.11 on 2024-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_part_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='projectImage',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Project Image'),
            preserve_default=False,
        ),
    ]
