# Generated by Django 4.2.11 on 2024-05-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_fiber_price21_fiber_price22_fiber_price23_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resin',
            old_name='Hardness',
            new_name='hardness',
        ),
    ]
