# Generated by Django 4.2.11 on 2024-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_rename_hardness_resin_hardness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resin',
            name='hardener',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resin system - Hardener'),
        ),
        migrations.AlterField(
            model_name='resin',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='resin',
            name='resin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resin system - Resin'),
        ),
    ]
