# Generated by Django 4.2.11 on 2024-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_project_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lastUpdate',
            field=models.DateField(blank=True, null=True, verbose_name='Last Update M/D/Y'),
        ),
    ]
