# Generated by Django 4.2.11 on 2024-05-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_project_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_and_d',
            name='FVRC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='agedC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='brakeForcebobinC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='compositeDensityC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='compressionUltimateLoadC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='compressionUltimateStressC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='compressionUltimateStressMAC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='compressionUltimateStressMBC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='compressionYieldLoadC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='compressionYieldStressC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='compressionYieldStressMAC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='compressionYieldStressMBC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='compressionYoungModulusC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='configurarionC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='endEffectorC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='entryNozzleDiamC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='exitNozzleDiamC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='experimentalSampleSectionC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='fiberC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='flexuralModulusFC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='flexuralModulusILSSC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='flexuralUltimateForceC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='flexuralUltimateStrengthC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='flexuralUltimateStrengthMAC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='flexuralUltimateStrengthMBC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='impregnationBathC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='maxiTorqueC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='maxiTwistedAngleC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='numberOfBobbinsC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='numberOfCyclesC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='numberOfSamplesC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='poissonRatioC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='porosityC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='resinC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='roomTemperatureC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='roomhumidityC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='sampleLengthC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='sleeveC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='strainUltimateStrengthC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='temperatureOfTestsC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='tensileUltimateLoadC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='tensileUltimateStressC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='tensileUltimateStressMAC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='tensileUltimateStressMBC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='tensileYieldLoadC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='tensileYieldStressC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='tensileYieldStressMAC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='tensileYieldStressMBC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='tensileYoungModulusC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='theoreticalSampleSectionC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='thermalConductivityC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='thermalExpansionCoefficientC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='ultimateShearForceC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='ultimateShearStressC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='ultimateShearStressMAC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='ultimateShearStressMBC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='windingSpeedRangeC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='yieldAngleC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='yieldTorqueC',
            field=models.CharField(blank=True, default='Samples number: ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rdcomment',
            name='approvedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rdcomment',
            name='lastUpdate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rdcomment',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rdcomment',
            name='projectNr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rdcomment',
            name='verifiedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
