# Generated by Django 4.2.11 on 2024-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_r_and_d_fvrc_r_and_d_agedc_r_and_d_brakeforcebobinc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_and_d',
            name='curingCycleC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='fiberDensityC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='hardenerC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='resinDensityC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='texC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='towC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='RDComment',
        ),
    ]
