# Generated by Django 4.2.11 on 2024-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_r_and_d_curingcyclec_r_and_d_fiberdensityc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_and_d',
            name='program',
            field=models.CharField(default=1, max_length=255, verbose_name='Program :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='r_and_d',
            name='projectNr',
            field=models.CharField(default=1, max_length=255, verbose_name='Project Nr. :'),
            preserve_default=False,
        ),
    ]
