# Generated by Django 4.2.11 on 2024-05-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_r_and_d_program_alter_r_and_d_projectnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_and_d',
            name='ERMDS',
            field=models.CharField(max_length=255, verbose_name='ERMDS Nr. :'),
        ),
    ]
