# Generated by Django 4.2.11 on 2024-05-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_alter_r_and_d_ermds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequenceType', models.CharField(max_length=255, unique=True, verbose_name='Sequence Type')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='partName',
            field=models.CharField(max_length=255, verbose_name='Part Name'),
        ),
        migrations.AlterField(
            model_name='winding',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sequencetype', verbose_name='WindingType Description'),
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
    ]
