# Generated by Django 4.2.11 on 2024-05-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_fiber_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiber',
            name='distributor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Distributor'),
        ),
    ]
