# Generated by Django 4.2.11 on 2024-05-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_winding_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winding',
            name='interface',
        ),
        migrations.AddField(
            model_name='winding',
            name='interface1',
            field=models.CharField(default=1, max_length=255, verbose_name='Interface Start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winding',
            name='interface2',
            field=models.CharField(default=1, max_length=255, verbose_name='Interface Transition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winding',
            name='interface3',
            field=models.CharField(default=1, max_length=255, verbose_name='Interface End'),
            preserve_default=False,
        ),
    ]
