# Generated by Django 4.2.11 on 2024-06-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_remove_winding_interface_winding_interface1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_and_d',
            name='fiberC',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
