# Generated by Django 4.2.11 on 2024-06-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_r_and_d_fiberc'),
    ]

    operations = [
        migrations.AddField(
            model_name='resin',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
