# Generated by Django 4.2.11 on 2024-06-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_resin_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bushing',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiber',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interface',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='r_and_d',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequencetype',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='winding',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
