# Generated by Django 4.2.11 on 2024-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_bushing_valid_fiber_valid_interface_valid_link_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bushing',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='fiber',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='link',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='part',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='r_and_d',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='resin',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='sequencetype',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='winding',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Validation'),
        ),
    ]
