# Generated by Django 4.2.11 on 2024-06-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_winding_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_and_d',
            name='ERMDS',
            field=models.CharField(max_length=255, verbose_name='ERMDS Nr. '),
        ),
        migrations.AlterField(
            model_name='r_and_d',
            name='approvedBy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Approved by '),
        ),
        migrations.AlterField(
            model_name='r_and_d',
            name='lastUpdate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last update '),
        ),
        migrations.AlterField(
            model_name='r_and_d',
            name='program',
            field=models.CharField(max_length=255, verbose_name='Program '),
        ),
        migrations.AlterField(
            model_name='r_and_d',
            name='projectNr',
            field=models.CharField(max_length=255, verbose_name='Project Nr. '),
        ),
        migrations.AlterField(
            model_name='r_and_d',
            name='verifiedBy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Verified by'),
        ),
    ]
