# Generated by Django 4.2.11 on 2024-06-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_alter_r_and_d_ermds_alter_r_and_d_approvedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of members'),
        ),
    ]
