# Generated by Django 4.2.11 on 2024-06-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_department_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='number',
        ),
    ]
