from django_medusa.renderers import StaticSiteRenderer
from django.urls import reverse

class MyStaticRenderer(StaticSiteRenderer):
    def get_paths(self):
        return [
            reverse('documentation', kwargs={'path': ''}),
            reverse('updateDoc'),
            reverse('home0'),
            reverse('login'),
            reverse('logout'),
            reverse('img_code'),
            reverse('home'),
            reverse('upload'),
            reverse('check'),
            reverse('changePassword', kwargs={'aid': 1}),
            reverse('user_log'),
            reverse('fiber_list'),
            reverse('fiber_valid'),
            reverse('fiber_add'),
            reverse('fiber_add_multiple'),
            reverse('fiber_edit', kwargs={'aid': 1}),
            reverse('fiber_delete'),
            reverse('fiber_modify_multiple'),
            reverse('resin_list'),
            reverse('resin_list_mechanical_properties'),
            reverse('resin_list_thermophysical_toughness_properties'),
            reverse('resin_valid'),
            reverse('resin_valid_mechanical_properties'),
            reverse('resin_valid_thermophysical_toughness_properties'),
            reverse('resin_add'),
            reverse('resin_add_multiple'),
            reverse('resin_add_mechanical_properties'),
            reverse('resin_add_thermophysical_toughness_properties'),
            reverse('resin_edit', kwargs={'aid': 1}),
            reverse('resin_delete'),
            reverse('resin_modify_multiple'),
            reverse('resin_modify_mechanical_properties'),
            reverse('resin_modify_thermophysical_toughness_properties'),
            reverse('r_and_d_list'),
            reverse('r_and_d_valid'),
            reverse('r_and_d_add'),
            reverse('r_and_d_edit', kwargs={'aid': 1}),
            reverse('r_and_d_delete'),
            reverse('get_fiber_data', kwargs={'fiber_id': 1}),
            reverse('get_resin_data', kwargs={'resin_id': 1}),
            reverse('project_list'),
            reverse('project_valid'),
            reverse('project_add'),
            reverse('project_edit', kwargs={'aid': 1}),
            reverse('project_delete'),
            reverse('upload_file_project'),
            reverse('download_projects_pdf'),
            reverse('part_list'),
            reverse('part_list_doc'),
            reverse('part_valid'),
            reverse('part_valid_doc'),
            reverse('part_add'),
            reverse('part_edit', kwargs={'aid': 1}),
            reverse('part_edit_doc', kwargs={'aid': 1}),
            reverse('part_delete'),
            reverse('upload_file_part'),
            reverse('download_parts_pdf'),
            reverse('bushing_list'),
            reverse('bushing_valid'),
            reverse('bushing_add'),
            reverse('bushing_edit', kwargs={'aid': 1}),
            reverse('bushing_delete'),
            reverse('load_parts'),
            reverse('bushing_add_multiple'),
            reverse('bushing_modify_multiple'),
            reverse('upload_file_bushing'),
            reverse('download_bushings_pdf'),
            reverse('interface_list'),
            reverse('interface_valid'),
            reverse('interface_add'),
            reverse('interface_edit', kwargs={'aid': 1}),
            reverse('interface_delete'),
            reverse('interface_add_multiple'),
            reverse('interface_modify_multiple'),
            reverse('upload_file_interface'),
            reverse('download_interfaces_pdf'),
            reverse('link_list'),
            reverse('link_valid'),
            reverse('link_add'),
            reverse('link_edit', kwargs={'aid': 1}),
            reverse('link_delete'),
            reverse('link_add_multiple'),
            reverse('link_modify_multiple'),
            reverse('upload_file_link'),
            reverse('download_links_pdf'),
            reverse('winding_list'),
            reverse('winding_valid'),
            reverse('winding_add'),
            reverse('winding_edit', kwargs={'aid': 1}),
            reverse('winding_delete'),
            reverse('winding_add_multiple'),
            reverse('winding_modify_multiple'),
            reverse('user_list'),
            reverse('user_list_read'),
            reverse('user_edit', kwargs={'aid': 1}),
            reverse('user_delete'),
            reverse('user_add_multiple'),
            reverse('user_modify_multiple'),
            reverse('department_list'),
            reverse('department_list_read'),
            reverse('department_edit', kwargs={'aid': 1}),
            reverse('department_delete'),
            reverse('department_add_multiple'),
            reverse('department_modify_multiple'),
            reverse('sequenceType_list'),
            reverse('sequenceType_valid'),
            reverse('sequenceType_edit', kwargs={'aid': 1}),
            reverse('sequenceType_delete'),
            reverse('sequenceType_add_multiple'),
            reverse('sequenceType_modify_multiple'),
            reverse('download_sequenceTypes_pdf'),
            
        ]

renderers = [MyStaticRenderer,]
